# Generated by Django 5.1.3 on 2024-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suka', '0002_cart_session_key_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='Guest', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default='No Address Provided', null=True),
        ),
    ]
