# Generated by Django 5.1.3 on 2024-11-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suka', '0003_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
